### PR TITLE
Add example use case for require="isFalse"

### PR DESCRIPTION
**Pull request by silvenon**
Let me know if I got it right :wink:

### CODE REVIEW

**Comment by christianalfoni** [comment]
Sorry for very late reply, but this is great, thanks! :-)

**Comment by silvenon** [comment]
Or is it **unchecked**?

**Comment by christianalfoni** [comment]
Hehe, I think this is right. You state what rule it needs to match to indicate that it is required. And that is when it is "isFalse", when checkbox is unchecked... but "required to be checked" is the opposite, so yeah, correct :-) Ah, validation is hard! :-D

**Comment by silvenon** [comment]
Indeed!

**Pull request merged**
