### PR TITLE
Bugfix: show the default validation message when there is a required error

### PR DESCRIPTION
**Pull request by wuct**

### CODE REVIEW

**Comment by wuct** [comment]
Might related to #276.
However, `showError()` is still buggy.

**Comment by wuct** [comment]
OK, I manage to fix `showError()` by [this commit ](https://github.com/christianalfoni/formsy-react/pull/386/commits/4a580c26274f5d4d34c96a5e187b27af981938eb).

**Comment by valorize** [comment]
@christianalfoni Works for me.

**Comment by aesopwolf** [comment]
Thanks @wuct, just published `v0.19.1` with this in it https://www.npmjs.com/package/formsy-react

**Comment by wuct** [comment]
Thanks for merging

**Pull request merged**
