### PR TITLE
Update to React 15.0.1

### PR DESCRIPTION
**Pull request by kremez19**
#324

### CODE REVIEW

**Comment by cumbreras** [comment]
Nice one!

**Comment by Semigradsky** [comment]
Thanks for your help! I updated Formsy, check new version.

**Comment by kremez19** [comment]
@Semigradsky sorry. Have you made ```npm publish```? As npm show 0.17.0 version as letest https://www.npmjs.com/package/formsy-react

**Comment by Semigradsky** [comment]
@kremez19 I'm sorry, my mistake. Check now

**Pull request closed without merging**
