### PR TITLE
Fix crash when comparing array with null

### PR DESCRIPTION
**Pull request by davidblurton**
When comparing Array with null, the `isSame` method would call `.length` on `null`, which crashed.

### CODE REVIEW

**Comment by davidblurton** [comment]
Rebased and ran `npm run deploy`. @aesopwolf PTAL

**Comment by aesopwolf** [comment]
Thanks. Not sure if it makes sense for PR's to commit release files though. I think `npm run deploy` should be something we run when we're ready to deploy a new version. So, after x new features or every x weeks.

Plus it seems like a pain for contributors to have go through.

What are your thoughts? (I was just made a collaborator on the project and you seem to have some previous contributions so I'd like to get your feedback 🙂)

**Comment by davidblurton** [comment]
Yeah I agree, I just ran it because the last time I contributed I was asked to build these files. 

The only downside to not committing these files is that you can't use your fork while you're waiting for a PR to be merged.

However, not including these files in PRs will make them easier to merge more quickly.

**Comment by aesopwolf** [comment]
Ah that's a good point about being able to use your fork, I didn't think of that. I guess we can leave the release files as 'optional' for PRs.

I'll go ahead and merge this as is.

**Pull request merged**
