### PR TITLE
Removed 'required' check from validations

### PR DESCRIPTION
**Pull request by Semigradsky**
#114 + added tests

### CODE REVIEW

**Comment by Semigradsky** [comment]
Should fix #113

**Comment by sanemat** [comment]
@Semigradsky 
I have a question.

This pull request's behavior
```
<TestInput
  name="foo" 
  validations="isLength:3" />

//valid
'sup'
//invalid
'hi', 'foo bar', undefined, null, ''
```

But I think this is expected. What do you think?

```
// no-required
<TestInput
  name="foo"
  validations="isLength:3" />

//valid
'sup', ''
//invalid
'hi', 'foo bar', undefined, null

// --------
// required
<TestInput
  name="foo"
  validations="isLength:3"
  required />

//valid
'sup'
//invalid
'hi', 'foo bar', undefined, null, ''
```

**Comment by Semigradsky** [comment]
>
```js
//valid
'sup', ''
```

That is confused me. Length of empty string is not 3 ;)

@sanemat  How about extending the syntax?
```js
<TestInput
  name="foo" 
  validations="isLength:0:3" />
```
and
```js
<TestInput
  name="foo" 
  validations={{
    isLength: [0, 3]
  }} />
```
This should not be difficult to implement)

**Comment by sanemat** [comment]
> Length of empty string is not 3 ;)

My question is unclear. Sorry. Length of empty string is not 3.

**Comment by christianalfoni** [comment]
Hi there,

Thanks for discussing this. It has been a bit difficult identifying required/validation regarding "empty values" as formsy supports any kind of form element, not just traditional inputs.

But we are getting there :-)

**Pull request merged**
