### PR TITLE
* Fixed mapModel issue when input name is nested

### PR DESCRIPTION
**Pull request by garbin**
you mentioned on https://github.com/christianalfoni/formsy-react/issues/120#issuecomment-104647908 has bug
My code is
```
<input name="product" />
<input name="stock.price" />
<input name="stock.sku" />
```
mappedModel should be
```
{
   product_name:...,
   stock:{
      price: ...,
      sku: ...
   }
}
```
But In my situation, the mappedModel is
```
{
    price: ...
    sku:....
    product_name: ...
    stock:{}
}
```
So I created this PR to fixed it.

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @garbin , great! Thanks. Working on a new version of formsy now, going through all open issues and adding support for React 0.14, adding support for the new parent-child context relationship

**Comment by rblakeley** [comment]
Is Array support not included? My use case is:
```
{
  foo: ['','']
}
...
name='foo[0]'
name='foo[1]'
```

This PR allows:
```
{
  foo: {
    0: '',
    1: ''
  }
}
...
name='foo.0'
name='foo.1'
```

But if your API wants an Array, you have to parse it somewhere else. Which is why support for an Array-like string would be good.

**Comment by rblakeley** [comment]
@garbin @christianalfoni 
The `inputs` parameter for the handler `props.mapping` is not getting mapped for nested objects like `this.model`.
```
// inputs
{
  'foo.0': '',
  'foo.1': ''
}

// this.model
{
  foo: {
    0: '',
    1: ''
  }
}
Is this intentional or a bug?

**Comment by garbin** [comment]
I think this is a new feature that needs to be discussed.

**Comment by christianalfoni** [comment]
Hi!

Yeah, @rblakeley, please set up a new issue on that. Currently it just builds objects by splitting on `.`. It was implemented like this based on a discussion, but lets review it :-)

**Pull request merged**
