### PR TITLE
Add method for checking if input has had interaction

### PR DESCRIPTION
**Pull request by FoxxMD**
Address issue #10 

* Input state has `isPristine` to represent user interaction
* `isPristine` defaults to `true`
* Is triggered by `setValue` to `false`
* Reset on `resetValue`
* `setFormPristine` sets all form inputs pristine value
* `onSubmit` sets `setFormPristine` false

### CODE REVIEW

**Comment by FoxxMD** [comment]
Woops my commit message has true and false backward for the 2nd and 3rd bullet point! But it's correct in the code.

**Comment by christianalfoni** [comment]
Ah, awesome, here it is :-)

I will go through it tomorrow and create a new release. Thank you! :-)

**Comment by christianalfoni** [comment]
This looks great! Thanks :-) Writing some tests and adding a couple of other things and will make a new release!

**Comment by FoxxMD** [comment]
:+1:

**Pull request merged**
