### PR TITLE
Fix multiple on change

### PR DESCRIPTION
**Pull request by sdemjanenko**

### CODE REVIEW

**Comment by valerymercury** [comment]
+1

**Comment by seburgi** [comment]
+1

**Comment by Semigradsky** [comment]
@sdemjanenko Hi! Thanks for PR
Could you use spread syntax instead adding new dependency?
https://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx

```
var {
      mapping,
      validationErrors,
      onSubmit,
      onValid,
      onInvalid,
      onInvalidSubmit,
      onChange,
      reset,
      preventExternalInvalidation,
      onSuccess,
      onError,
      ...nonFormsyProps
} = this.props;

**Comment by sdemjanenko** [comment]
@Semigradsky: updated.

**Comment by Semigradsky** [comment]
Nice!

**Comment by valerymercury** [comment]
Can you update npm version please ?

**Comment by Semigradsky** [comment]
I can't. Ping @christianalfoni

**Comment by sb2nov** [comment]
@christianalfoni ping on new release ?

**Comment by sb2nov** [comment]
@christianalfoni ping^

**Comment by mciastek** [comment]
@christianalfoni ping

**Pull request merged**
