### PR TITLE
React 0.14

### PR DESCRIPTION
**Pull request by davidblurton**
Merge master into react-0.14

Updated to latest beta version
Use `react-dom` for rendering html
Fix warnings in examples

### CODE REVIEW

**Comment by christianalfoni** [comment]
Awesome stuff, thanks! Hopefully we are right around the corner for React 0.14 and can officially release :-)

**Comment by davidblurton** [comment]
Great - can you publish this as a beta version to npm?

**Comment by christianalfoni** [comment]
You know how that works? Trying to find some documentation. Thought I could just checkout the branch and publish it with `--tag beta`?

**Comment by davidblurton** [comment]
Yup, just use `npm publish --tag beta` and it won't be installed by default.

**Comment by christianalfoni** [comment]
Hm, for some reason it states that I can not publish over the previous version. Maybe I still have to give it a new version number, but using --tag beta it will not be installed by default?

**Comment by davidblurton** [comment]
Yeah, change the version number to `0.14.1-beta1` or something. Unfortunate version number coincidence with react 0.14 :)

**Comment by christianalfoni** [comment]
ah, yes, there we go:

`npm install formsy-react@beta` :-)

**Comment by davidblurton** [comment]
nice - thanks!

**Comment by christianalfoni** [comment]
Would be great if you could confirm that everything works as expected, and especially if not :-)

**Comment by davidblurton** [comment]
Not working - fixed in https://github.com/christianalfoni/formsy-react/pull/193

**Pull request merged**
