### PR TITLE
Allow form to be initialised with specified data

### PR DESCRIPTION
**Pull request by tomaash**
Modify reset function so that it accepts argument with data model that the form should be initialised with. This comes handy when you want to edit an object to have the form prefilled with object data by just passing the object to reset function instead of filling the fields manualy.

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @tomaash and thanks for the pull!

I agree this should be in there, but I have a suggestion for you. Since the goal here is to set some initial values, maybe we should put:

```js
<Formsy.Form values={{
  foo: 'bar',
  bar: 'foo'
}}>
  <MyInput name="foo"/>
  <MyInput name="bar"/>
</Formsy.Form>
```
That way it is very specific to what you want to achieve. We could of course also merge in your change, as you still might need to reset the values easily :-)

**Comment by tomaash** [comment]
Yes, exactly. Having the values in markup is not sufficient, I need to set them during runtime. Of course, api can be different. For example, there could be a new method called "setValues" or something. But passing argument to reset felt natural enough to me.

**Comment by tomaash** [comment]
So what do you think? I can has merge?

**Comment by tomaash** [comment]
@christianalfoni can we merge this please? I already had to pull upstream to have some other bugs fixed in my brach. I'd really prefer to have this change there. Thanks..

**Comment by christianalfoni** [comment]
Hi @tomaash , so sorry for late reply, but I have been completely in loss of time the last week. I will release a new version tomorrow morning including your fix!

**Comment by tomaash** [comment]
Cool, thanks!

**Comment by vijayrawatsan** [comment]
I tried this.refs.form.reset(model). Value passed in the model does attach to textfields but it does not reflect in the ui.

**Comment by tomaash** [comment]
It works for me, but I did not try in the latest version. Also, check if your formsy inputs are sane, and if render method gets called properly.

**Comment by vijayrawatsan** [comment]
I am using formsy-react 0.14.1 & formsy-material-ui 0.2.2
```javascript
componentDidMount: function(nextProps) {
        this.resetForm({
            'name': 'asd',
            'email': 'asd@asd.com'
        });
    },
resetForm: function (model) {
        this.refs.form.reset(model);
    },
submitForm: function (model) {
        console.log(model);
    } 
```
When I submit I could see asd and asd@asd.com, but I can not see the value in the form itself.

**Comment by tomaash** [comment]
I'd try to debug formsy-material-ui, their inputs might rely on some other mechanism to re-render.

**Comment by vijayrawatsan** [comment]
@tomaash Thanks :+1:

**Comment by vijayrawatsan** [comment]
By the way, is there any other hackish way of prefilling the values? I am kind of on a strict timeline.

**Comment by tomaash** [comment]
@vijayrawatsan How about executing resetForm earlier, for example in `componentWillReceiveProps` or `componentWillMount` ? If this does not help try another formsy inputs. If this does not help, try it with https://github.com/twisty/formsy-react-components or with the sample input from initial documentation - if those works, you can track down the difference or make your own component from it and restyle it.

**Comment by vijayrawatsan** [comment]
@tomaash I solved it in formsy-material-ui. https://github.com/mbrookes/formsy-material-ui/pull/10/files
Thanks a lot for the help. :santa:

**Comment by tomaash** [comment]
That was quite an omission there. Good job! :+1:

**Comment by utkuturunc** [comment]
@tomaash I am having a very similar issue to @vijayrawatsan. I added getValue() and setValue(), but event the simplest custom input component of mine is doing this.

If I reset a form, all boxes in the ui gets emptied. Then when I type on any one of the inputs, all other fields get set to correct reset values.

If I reset the form in setTimeout, fields blink for a moment but they get the correct values in.

The problem is 
If I want to reset to an empty form (create forms) resetting in timeout will not work.
If I want to reset to initial values (update forms) resetting outside timeout will not work.

Having both of them makes the form very unstable.

Either way I don't want to have timeout as a workaround.

**Pull request merged**
