### PR TITLE
Provide solution for dealing with ref problem when using HOC

### LINKED ISSUE #308: How to retrieve ref to input when HOC used
When defining an input class as lower order component of Formsy, how does one go about retrieving a ref to the underlying input component?

If an input class is simply:

``` javascript
class Input {
  render() {
    return (<div><label ...props>{this.props.caption}</label><input ...props/></div>);
}

export default Formsy.HOC(Input);
```

And the form:

``` javascript
class AForm {
  componentWillReceiveProps() {
    // How to access the input component? this.refs.input refers to the HOC of Input.
  }

  render() {
    return (
      <Form>
        <Input ref="input" ...props/>
      </Form>
    );
  }
}
```

Say I would like the Input class to allow for the focus to be set programmatically on its {input,textarea} element; how would I go about doing so? How would such an interface be exposed from `Input` above?

### LINKED ISSUE #341: Assign ref to formsy elements when using HOC or Decorator
When using the HOC or Decorator we are loosing the refs from children components when creating the new component with React.createClass, the newly component should have a ref like 'formsyElement'.

I fixed this but its hackish:

``` javascript
Formsy.Decorator = function () {
  return function (Component) {
    return React.createClass({
      mixins: [Formsy.Mixin],
      render: function () {
        return React.createElement(Component, {
          setValidations: this.setValidations,
          setValue: this.setValue,
          resetValue: this.resetValue,
          getValue: this.getValue,
          hasValue: this.hasValue,
          getErrorMessage: this.getErrorMessage,
          getErrorMessages: this.getErrorMessages,
          isFormDisabled: this.isFormDisabled,
          isValid: this.isValid,
          isPristine: this.isPristine,
          isFormSubmitted: this.isFormSubmitted,
          isRequired: this.isRequired,
          showRequired: this.showRequired,
          showError: this.showError,
          isValidValue: this.isValidValue,
          ref: 'formsyElement',
          ...this.props
        })
      }
    })
  }
}
```

With that changes I can now get the refs from the formsy element like `this.refs.autocomplete.refs.formsyElement.refs.input` for creating a new google autocomplete.

Thanks

### PR DESCRIPTION
**Pull request by aesopwolf**
Add method to expose the wrapped instance when using the HOC (higher order component)

It's `ref`'s all the way down. This closes #308, closes #341

### CODE REVIEW

**Comment by aesopwolf** [comment]
pinging @christianalfoni do you need additional maintainers for this project?

**Comment by aesopwolf** [comment]
I came across a different approach that might be slightly better, which is to pass a prop called `innerRef` that takes a function just like the normal `ref` prop. A full example can be seen here https://github.com/styled-components/styled-components/pull/122

What do you think @christianalfoni?

**Comment by aesopwolf** [comment]
@Semigradsky are you able to chime in here and help approve this?

**Comment by brianfegan** [comment]
Is there any movement on this? I'm seeing this as a blocker to being able to reset a multi checkbox group of checkbox inputs to their initial state. While this.refs.form.reset() will reset the overall form value to that initial state, the HOC wrapped checkboxes still remain checked.

**Comment by aesopwolf** [comment]
No movement. I haven't heard anything from the maintainers since opening the PR. They seem to have abandoned the project.

I'm debating forking it and getting a majority of the other PR's merged in as well.

**Comment by aesopwolf** [comment]
I pulled the trigger and forked the repo. I published it to npm under `formsy` (can't believe it was available!). I also merged in this PR to the new fork.

You can check it out here:

- https://www.npmjs.com/package/formsy
- https://github.com/aesopwolf/formsy

I think I'll make an issue to advertise the new fork and it's location.

**Comment by aesopwolf** [comment]
I was given write access to the repo (see https://github.com/christianalfoni/formsy-react/issues/411). So I'm going to reopen this PR and get it merged in.

**Pull request merged**
